### ISSUE TITLE
otbm editor

### ISSUE THREAD

**Issue by Raggaer** [TibiaJS/ideas#10]
What about a otbm map editor using node-webkit?
I dont really know any of the otbm protocol so I guess it can be hard as fuck but meh why not? this could lead us to using socket.io for mapping streaming or maybe work 2+ people on the same map real time

**Comment by gpedro** [comment]
Please, look this:
https://github.com/Sleavely/OTWorlds

we can understand how the OTWorlds and create our own implementation with node backend

**Comment by Raggaer** [comment]
https://github.com/Sleavely/OTWorlds/blob/master/app/libraries/POT/OTS_OTBMFile.php this can also help

**Comment by gpedro** [comment]
better yet, how about a OTServSDK.JS?

**Comment by Raggaer** [comment]
By that you mean...? that can hold too much

**Comment by gpedro** [comment]
module with sets of functions that assist the implementation of something or defining default values

**Comment by Raggaer** [comment]
No. I mean what should the sdk include?

**Comment by gpedro** [comment]
functions:
- map
  - houses
  - towns
  - map manipulation(binary)
- player
  - outfit
  - storage
  - skills
- database
  - reports

**Comment by Raggaer** [comment]
By the players functions what should those do? :+1:
